spring:
  application:
    name: notification-service
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/notification-service?authSource=admin
server:
  port: 8082
  servlet:
    context-path: /notification
email:
  service:
    url: https://api.brevo.com
    api-key: your-api-key
    sender:
      email: your-email
      name: your-name